[pytest]
markers =
    T1: core/basic tests for the assignment
    T2: edge-case tests for the assignment
    T3: optional bonus tests for the assignment
    T4: optional bonus tests for the assignment
